OC.L10N.register(
    "flow_notifications",
    {
    "Send a notification" : "إرسال إشعار",
    "Triggers a notification" : "إطلاق إشعار",
    "Flow Notifications" : "إشعارات أتمتة سير العمل",
    "Notification action for Nextcloud Flow" : "إجراء الإشعار بأتمتة سير العمل في نكست كلاود",
    "Enable users to configure notifications with customized conditions in their Flow configuration.\n\nUsers are empowered to configure a \"Send a notification\" Flow in their personal settings. They can choose between the events being triggered, and other conditions like filetypes, assigned tags, time ranges and more. They can specify an inscription so that when the notification appears they will have context.\n\nTo use the `Flow Notifications` app, ensure that the `Notifications` app is installed and enabled. The `Notifications` app provides the necessary APIs for the `Flow Notifications` app to work correctly.\n\n![Notification Flow Configuration](https://raw.githubusercontent.com/nextcloud/flow_notifications/master/screenshots/configuration.png)\n\nWhen an event happens where all conditions are apply, the user will receive a regular Nextcloud notification.\n\n![Flow Notification](https://raw.githubusercontent.com/nextcloud/flow_notifications/master/screenshots/notification.png)" : "تمكين المستخدمين من تكوين الإشعارات بشروط مخصصة لهم في تكوين التدفق الخاص بهم. \n\nيمكن للمستخدمين تكوين تدفق \"إرسال إشعار send a notification\" في إعداداتهم الشخصية. يمكنهم الاختيار بين الأحداث التي يتم إطلاقها، والشروط الأخرى مثل أنواع الملفات، و الوسوم المعينة، ونطاقات الوقت و غيرها. كما يمكنهم اختيار وصف للحدث بحيث يتعرفون على سياق الحدث عند ظهور الإشعار. \n\nلاستخدام تطبيق `تدفق الإشعارات Flow Notifications`، تأكد من تثبيت تطبيق `الإشعارات Notifications` وتمكينه. يوفر تطبيق \"الإشعارات\" واجهات برمجة التطبيقات اللازمة لتطبيق \"Flow Notifications\" للعمل بشكل صحيح. \n\n![تهيئة تدفق الإشعارات](https://raw.githubusercontent.com/nextcloud/flow_notifications/master/screenshots/configuration.png) \nعندما يحدث حدث حيث تنطبق جميع الشروط، سيتلقى المستخدم إشعاراً من نكست كلاود. \n\n![إشعار التدفق](https://raw.githubusercontent.com/nextcloud/flow_notifications/master/screenshots/notification.png)",
    "Choose a notification title (optional)" : "إختر عنواناً للإشعار (إختياري)",
    "Enable users to configure notifications with customized conditions in their Flow configuration.\n\nUsers are empowered to configure a \"Send a notification\" Flow in their personal settings. They can choose between the events being triggered, and other conditions like filetypes, assigned tags, time ranges and more. They can specify an inscription so that when the notification appears they will have context.\n\n![Notification Flow Configuration](https://raw.githubusercontent.com/nextcloud/flow_notifications/master/screenshots/configuration.png)\n\nWhen an event happens where all conditions are apply, the user will receive a regular Nextcloud notification.\n\n![Flow Notification](https://raw.githubusercontent.com/nextcloud/flow_notifications/master/screenshots/notification.png)" : "لتمكين المستخدمين من تهيئة الإشعارات المرسلة إليهم عن طريق وضع اشتراطات مُخصّصة لتهيئة إرسال تلك الإشعارات. \nيمكن للمستخدمين تهيئة عمليات الإرسال \"إرسال إشعار\" من إعداداتهم الشخصية؛ و ذلك باختيار الحدث الذي سيؤدّي إلى إطلاق الإشعار، و اشتراطاتٍ أخرى للإطلاق مثل نوع الملف، و سِماته tags، و المدى الزمني لتعديل أو إنشاء الملف و غيرها. كما يمكنهم إدراج خانة تسمح لهم بتذكُّر السياق المقصود في الإشعار.\n\n![تهيئة إرسال الإشعارات]\nأنظر (https://raw.githubusercontent.com/nextcloud/flow_notifications/master/screenshots/configuration.png)\n\nعند وقوع الحدث و تحقق جميع الاشتراطات، عندها يستلم المستخدم إشعاره من نكست كلاود.\n\n![إرسال الإشعارات] \nأنظر (https://raw.githubusercontent.com/nextcloud/flow_notifications/master/screenshots/notification.png)"
},
"nplurals=6; plural=n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 && n%100<=10 ? 3 : n%100>=11 && n%100<=99 ? 4 : 5;");
