OC.L10N.register(
    "flow_notifications",
    {
    "Send a notification" : "Enviar una notificación",
    "Triggers a notification" : "Provoca una notificación",
    "Flow Notifications" : "Flow Notifications",
    "Notification action for Nextcloud Flow" : "Acciones de notificación para Nextcloud Flow",
    "Enable users to configure notifications with customized conditions in their Flow configuration.\n\nUsers are empowered to configure a \"Send a notification\" Flow in their personal settings. They can choose between the events being triggered, and other conditions like filetypes, assigned tags, time ranges and more. They can specify an inscription so that when the notification appears they will have context.\n\nTo use the `Flow Notifications` app, ensure that the `Notifications` app is installed and enabled. The `Notifications` app provides the necessary APIs for the `Flow Notifications` app to work correctly.\n\n![Notification Flow Configuration](https://raw.githubusercontent.com/nextcloud/flow_notifications/master/screenshots/configuration.png)\n\nWhen an event happens where all conditions are apply, the user will receive a regular Nextcloud notification.\n\n![Flow Notification](https://raw.githubusercontent.com/nextcloud/flow_notifications/master/screenshots/notification.png)" : "Permite a los usuarios configurar las notificaciones mediante condiciones personalizadas en su configuración de Flujo.\n\nLos usuarios están autorizados a configurar un Flujo \"Enviar una notificación\" en sus ajustes personales. Pueden elegir entre los eventos que se activan y otras condiciones como tipos de archivos, etiquetas asignadas, rangos de tiempo y otras. Pueden especificar una inscripción de manera que cuando aparezca la notificación tengan un contexto.\n\nPara usar la app de `Flujo de Notificaciones`, asegúrese de que la aplicación de `Notificaciones` está instalada y habilitada. La app de `Notificaciones` proporciona las APIs necesarias para que la app de `Flujo de Notificaciones` funcione correctamente.\n\n![Configuración del flujo de notificación](https://raw.githubusercontent.com/nextcloud/flow_notifications/master/screenshots/configuration.png)\n\nCuando ocurra un evento en el que se apliquen todas las condiciones, el usuario recibirá una notificación en Nextcloud.\n\n![Notificación de flujo](https://raw.githubusercontent.com/nextcloud/flow_notifications/master/screenshots/notification.png)",
    "Choose a notification title (optional)" : "Elija un título para la notificación (opcional)"
},
"nplurals=3; plural=n == 1 ? 0 : n != 0 && n % 1000000 == 0 ? 1 : 2;");
