OC.L10N.register(
    "flow_notifications",
    {
    "Send a notification" : "Bidali jakinarazpen bat",
    "Triggers a notification" : "Jakinarazpen bat abiarazten du",
    "Flow Notifications" : "Fluxuaren jakinarazpenak",
    "Notification action for Nextcloud Flow" : "Nextcloud Flow-rako jakinarazpen ekintza",
    "Enable users to configure notifications with customized conditions in their Flow configuration.\n\nUsers are empowered to configure a \"Send a notification\" Flow in their personal settings. They can choose between the events being triggered, and other conditions like filetypes, assigned tags, time ranges and more. They can specify an inscription so that when the notification appears they will have context.\n\nTo use the `Flow Notifications` app, ensure that the `Notifications` app is installed and enabled. The `Notifications` app provides the necessary APIs for the `Flow Notifications` app to work correctly.\n\n![Notification Flow Configuration](https://raw.githubusercontent.com/nextcloud/flow_notifications/master/screenshots/configuration.png)\n\nWhen an event happens where all conditions are apply, the user will receive a regular Nextcloud notification.\n\n![Flow Notification](https://raw.githubusercontent.com/nextcloud/flow_notifications/master/screenshots/notification.png)" : "Gaitu erabiltzaileei beren fluxu konfigurazioan baldintza pertsonalizatuak dituzten jakinarazpenak konfiguratzeko.\n\nErabiltzaileak ahalmena dute \"Bidali jakinarazpen\" fluxua konfiguratzeko beren ezarpen pertsonaletan. Gertaeren artean hauteman daitezke, eta filetipoak bezalako beste baldintza batzuk, esleitutako etiketak, denbora-tarteak eta gehiago. Inskripzioa zehaztu dezakete jakinarazpenak testuingurua izango dutela.\n\n`Fluxu jakinarazpenen aplikazioa erabiltzeko, ziurtatu` jakinarazpenen aplikazioa instalatuta dagoela eta gaituta dagoela. `Jakinarazpenak 'aplikazioak beharrezko APIak hornitzen dizkio`Fluxuen jakinarazpenak' aplikazioa behar bezala funtziona dezan.\n\n! [Jakinarazpen-fluxuaren konfigurazioa] (https://raw.githubucontent.com/nextoudoud/flow_notifications/master/screenshots/configuration.png)\n\nBaldintza guztiak aplikatzen direnean gertaera batean, erabiltzaileak NextCloud jakinarazpen arrunta jasoko du.\n\n! [Fluxuaren jakinarazpena] (https://raw.githubucontent.com/nextoudoud/flow_notifications/master/screenshots/notification.png)",
    "Choose a notification title (optional)" : "Aukeratu jakinarazpen izenburua (aukerakoa)"
},
"nplurals=2; plural=(n != 1);");
