OC.L10N.register(
    "flow_notifications",
    {
    "Send a notification" : "Envoyer une notification",
    "Triggers a notification" : "Déclenche une notification",
    "Flow Notifications" : "Notifications de flux",
    "Notification action for Nextcloud Flow" : " Action de notification pour Nextcloud Flux",
    "Enable users to configure notifications with customized conditions in their Flow configuration.\n\nUsers are empowered to configure a \"Send a notification\" Flow in their personal settings. They can choose between the events being triggered, and other conditions like filetypes, assigned tags, time ranges and more. They can specify an inscription so that when the notification appears they will have context.\n\nTo use the `Flow Notifications` app, ensure that the `Notifications` app is installed and enabled. The `Notifications` app provides the necessary APIs for the `Flow Notifications` app to work correctly.\n\n![Notification Flow Configuration](https://raw.githubusercontent.com/nextcloud/flow_notifications/master/screenshots/configuration.png)\n\nWhen an event happens where all conditions are apply, the user will receive a regular Nextcloud notification.\n\n![Flow Notification](https://raw.githubusercontent.com/nextcloud/flow_notifications/master/screenshots/notification.png)" : "Permettez aux utilisateurs de configurer des notifications avec des conditions personnalisées dans leur configuration Flux.\n\nLes utilisateurs ont la possibilité de configurer un flux « Envoyer une notification » dans leurs paramètres personnels. Ils peuvent choisir entre les événements déclenchés et d'autres conditions telles que les types de fichiers, les étiquettes attribuées, les plages horaires, etc. Ils peuvent spécifier une inscription afin que la notification s'affiche avec son contexte.\n\nPour utiliser l'application « Notifications de Flux », assurez-vous que l'application « Notifications » est installée et activée. L'application « Notifications » fournit les API nécessaires au bon fonctionnement de l'application « Notifications de Flux ».\n\n![Configuration du notifications de Flux](https://raw.githubusercontent.com/nextcloud/flow_notifications/master/screenshots/configuration.png)\n\nLorsqu'un événement se produit et que toutes les conditions sont remplies, l'utilisateur recevra une notification Nextcloud classique.\n\n![Flow Notification](https://raw.githubusercontent.com/nextcloud/flow_notifications/master/screenshots/notification.png)",
    "Choose a notification title (optional)" : "Sélectionner un titre pour la notification (facultatif)"
},
"nplurals=3; plural=(n == 0 || n == 1) ? 0 : n != 0 && n % 1000000 == 0 ? 1 : 2;");
