OC.L10N.register(
    "flow_notifications",
    {
    "Send a notification" : "Seol fógra",
    "Triggers a notification" : "Spreagann sé fógra",
    "Flow Notifications" : "Fógraí Sreafa",
    "Notification action for Nextcloud Flow" : "Gníomh fógartha le haghaidh Nextcloud Flow",
    "Enable users to configure notifications with customized conditions in their Flow configuration.\n\nUsers are empowered to configure a \"Send a notification\" Flow in their personal settings. They can choose between the events being triggered, and other conditions like filetypes, assigned tags, time ranges and more. They can specify an inscription so that when the notification appears they will have context.\n\nTo use the `Flow Notifications` app, ensure that the `Notifications` app is installed and enabled. The `Notifications` app provides the necessary APIs for the `Flow Notifications` app to work correctly.\n\n![Notification Flow Configuration](https://raw.githubusercontent.com/nextcloud/flow_notifications/master/screenshots/configuration.png)\n\nWhen an event happens where all conditions are apply, the user will receive a regular Nextcloud notification.\n\n![Flow Notification](https://raw.githubusercontent.com/nextcloud/flow_notifications/master/screenshots/notification.png)" : "Cuir ar chumas úsáideoirí fógraí a chumrú le coinníollacha saincheaptha ina gcumraíocht Sreabhadh.\n\nTá sé de chumhacht ag úsáideoirí Sreabhadh \"Seol fógra\" a chumrú ina socruithe pearsanta. Is féidir leo rogha a dhéanamh idir na himeachtaí atá á dtionscnamh, agus coinníollacha eile amhail cineálacha comhaid, clibeanna sannta, raonta ama agus go leor eile. Is féidir leo inscríbhinn a shonrú ionas go mbeidh comhthéacs acu nuair a thaispeánfar an fógra.\n\nChun an aip `Flow Notices` a úsáid, cinntigh go bhfuil an aip `Fógraí` suiteáilte agus cumasaithe. Soláthraíonn an aip `Fógraí` na APInna riachtanacha chun go n-oibreoidh an aip `Flow Notifications` i gceart.\n\n![Cumraíocht Sreabhadh Fógra](https://raw.githubusercontent.com/nextcloud/flow_notifications/master/screenshots/configuration.png)\n\nNuair a tharlaíonn teagmhas ina bhfuil na coinníollacha go léir i bhfeidhm, gheobhaidh an t-úsáideoir fógra rialta Nextcloud.\n\n![Fógra faoi Shreabhadh](https://raw.githubusercontent.com/nextcloud/flow_notifications/master/screenshots/notification.png)",
    "Choose a notification title (optional)" : "Roghnaigh teideal fógra (roghnach)"
},
"nplurals=5; plural=(n==1 ? 0 : n==2 ? 1 : n<7 ? 2 : n<11 ? 3 : 4);");
