OC.L10N.register(
    "flow_notifications",
    {
    "Send a notification" : "Siųsti pranešimą",
    "Flow Notifications" : "„Eigos“ pranešimai",
    "Notification action for Nextcloud Flow" : "Pranešimo veiksmas, skirtas Nextcloud „Eigai“",
    "Enable users to configure notifications with customized conditions in their Flow configuration.\n\nUsers are empowered to configure a \"Send a notification\" Flow in their personal settings. They can choose between the events being triggered, and other conditions like filetypes, assigned tags, time ranges and more. They can specify an inscription so that when the notification appears they will have context.\n\nTo use the `Flow Notifications` app, ensure that the `Notifications` app is installed and enabled. The `Notifications` app provides the necessary APIs for the `Flow Notifications` app to work correctly.\n\n![Notification Flow Configuration](https://raw.githubusercontent.com/nextcloud/flow_notifications/master/screenshots/configuration.png)\n\nWhen an event happens where all conditions are apply, the user will receive a regular Nextcloud notification.\n\n![Flow Notification](https://raw.githubusercontent.com/nextcloud/flow_notifications/master/screenshots/notification.png)" : "Leiskite vartotojams konfigūruoti pranešimus su tinkintomis sąlygomis savo „Eigos“ konfigūracijoje.\n\nVartotojai gali konfigūruoti Eigos „Siųsti pranešimą“ savo asmeniniuose nustatymuose. Jie gali pasirinkti tarp suaktyvinamų įvykių ir kitų sąlygų, pvz., failų tipų, priskirtų žymų, laiko intervalų ir kt. Jie gali nurodyti užrašą, kad pasirodžius pranešimui, jie turėtų kontekstą.\n\nNorėdami naudoti programėlę „Eigos pranešimai“, įsitikinkite, kad programėlė „Pranešimai“ yra įdiegta ir įjungta. Programėlė „Pranešimai“ teikia reikiamas API, kad programėlė „Eigos pranešimai“ veiktų tinkamai.\n\n![Pranešimų Eigos konfigūracija](https://raw.githubusercontent.com/nextcloud/flow_notifications/master/screenshots/configuration.png)\n\nKai įvyksta įvykis, kai taikomos visos sąlygos, vartotojas gaus įprastą „Nextcloud“ pranešimą.\n\n![Eigos pranešimas](https://raw.githubusercontent.com/nextcloud/flow_notifications/master/screenshots/notification.png)"
},
"nplurals=4; plural=(n % 10 == 1 && (n % 100 > 19 || n % 100 < 11) ? 0 : (n % 10 >= 2 && n % 10 <=9) && (n % 100 > 19 || n % 100 < 11) ? 1 : n % 1 != 0 ? 2: 3);");
