OC.L10N.register(
    "flow_notifications",
    {
    "Send a notification" : "Enviar uma notificação",
    "Triggers a notification" : "Dispara uma notificação",
    "Flow Notifications" : "Notificações de Fluxo",
    "Notification action for Nextcloud Flow" : "Ação de notificação para o Nextcloud Fluxo",
    "Enable users to configure notifications with customized conditions in their Flow configuration.\n\nUsers are empowered to configure a \"Send a notification\" Flow in their personal settings. They can choose between the events being triggered, and other conditions like filetypes, assigned tags, time ranges and more. They can specify an inscription so that when the notification appears they will have context.\n\nTo use the `Flow Notifications` app, ensure that the `Notifications` app is installed and enabled. The `Notifications` app provides the necessary APIs for the `Flow Notifications` app to work correctly.\n\n![Notification Flow Configuration](https://raw.githubusercontent.com/nextcloud/flow_notifications/master/screenshots/configuration.png)\n\nWhen an event happens where all conditions are apply, the user will receive a regular Nextcloud notification.\n\n![Flow Notification](https://raw.githubusercontent.com/nextcloud/flow_notifications/master/screenshots/notification.png)" : "Permite que os usuários configurem notificações com condições personalizadas na configuração do Fluxo.\n\nOs usuários são incentivados a configurar \"Enviar uma notificação\" do Fluxo nas configurações pessoais. Eles podem escolher entre os eventos que estão sendo disparados e outras condições, como tipos de arquivos, etiquetas atribuídas, intervalos de tempo e muito mais. Eles podem especificar uma descrição para que, quando a notificação aparecer, eles tenham contexto.\n\nPara usar o aplicativo `Notificações de Flow`, assegure que o aplicativo `Notificações` esteja instalado e ativado. O apicativo `Notificações` fornece as APIs necessárias para que o aplicativo `Notificações de Fluxo` funcione corretamente. \n\n![Configuração do Fluxo de Notificações](https://raw.githubusercontent.com/nextcloud/flow_notifications/master/screenshots/configuration.png)\n\nQuando ocorre um evento em que todas as condições se aplicam, o usuário receberá uma notificação regular do Nextcloud.\n\n![Notificação do Fluxo](https://raw.githubusercontent.com/nextcloud/flow_notifications/master/screenshots/notification.png)",
    "Choose a notification title (optional)" : "Escolha o título da notificação (opcional)"
},
"nplurals=3; plural=(n == 0 || n == 1) ? 0 : n != 0 && n % 1000000 == 0 ? 1 : 2;");
