OC.L10N.register(
    "flow_notifications",
    {
    "Send a notification" : "Enviar uma notificação",
    "Triggers a notification" : "Aciona uma notificação",
    "Flow Notifications" : "Notificações  Flow",
    "Notification action for Nextcloud Flow" : "Ação de notificação para o Nextcloud Flow",
    "Enable users to configure notifications with customized conditions in their Flow configuration.\n\nUsers are empowered to configure a \"Send a notification\" Flow in their personal settings. They can choose between the events being triggered, and other conditions like filetypes, assigned tags, time ranges and more. They can specify an inscription so that when the notification appears they will have context.\n\nTo use the `Flow Notifications` app, ensure that the `Notifications` app is installed and enabled. The `Notifications` app provides the necessary APIs for the `Flow Notifications` app to work correctly.\n\n![Notification Flow Configuration](https://raw.githubusercontent.com/nextcloud/flow_notifications/master/screenshots/configuration.png)\n\nWhen an event happens where all conditions are apply, the user will receive a regular Nextcloud notification.\n\n![Flow Notification](https://raw.githubusercontent.com/nextcloud/flow_notifications/master/screenshots/notification.png)" : "Permitir que os utilizadores configurem notificações com condições personalizadas na sua configuração do Fluxo.\n\nOs utilizadores podem configurar um Fluxo \"Enviar uma notificação\" nas suas definições pessoais. Podem escolher entre os eventos que serão acionados e outras condições, como tipos de ficheiro, etiquetas atribuídas, intervalos de tempo e muito mais. Podem especificar uma descrição para que, quando a notificação aparecer, tenham contexto.\n\nPara utilizar a aplicação \"Notificação de Fluxo\", certifique-se de que a aplicação \"Notificações\" está instalada e ativada. A aplicação `Notificações` fornece as APIs necessárias para que a aplicação `Notificações de Fluxo` funcione corretamente.\n\n![Configuração do Fluxo de Notificações](https://raw.githubusercontent.com/nextcloud/flow_notifications/master/screenshots/configuration.png)\n\nQuando um evento ocorre e todas as condições são cumpridas, o utilizador receberá uma notificação normal do Nextcloud.\n\n![Notificação de Fluxo](https://raw.githubusercontent.com/nextcloud/flow_notifications/master/screenshots/notification.png)",
    "Choose a notification title (optional)" : "Escolha o título da notificação (opcional)"
},
"nplurals=3; plural=(n == 0 || n == 1) ? 0 : n != 0 && n % 1000000 == 0 ? 1 : 2;");
