OC.L10N.register(
    "flow_notifications",
    {
    "Send a notification" : "Пошаљи обавештење",
    "Triggers a notification" : "Окида обавештење",
    "Flow Notifications" : "Обавештења Тока",
    "Notification action for Nextcloud Flow" : "Акције обавештења за апликацију Обавештења Тока",
    "Enable users to configure notifications with customized conditions in their Flow configuration.\n\nUsers are empowered to configure a \"Send a notification\" Flow in their personal settings. They can choose between the events being triggered, and other conditions like filetypes, assigned tags, time ranges and more. They can specify an inscription so that when the notification appears they will have context.\n\nTo use the `Flow Notifications` app, ensure that the `Notifications` app is installed and enabled. The `Notifications` app provides the necessary APIs for the `Flow Notifications` app to work correctly.\n\n![Notification Flow Configuration](https://raw.githubusercontent.com/nextcloud/flow_notifications/master/screenshots/configuration.png)\n\nWhen an event happens where all conditions are apply, the user will receive a regular Nextcloud notification.\n\n![Flow Notification](https://raw.githubusercontent.com/nextcloud/flow_notifications/master/screenshots/notification.png)" : "Омогућава корисницима да подесе оабештења са произвољним условима у њиховим подешавањима апликације Ток.\n\nКорисници сада имају могућност да подесе „Пошаљи обавештење” Ток у својим личним поставкама. Могу одабрати између догађаја који се окидају и других услова као што су типови фајлова, додаљене ознаке, временски оквири и сл. Такође могу одабрати и натпис, тако да када се обавештења појаве, имају контекст.\n\nДа бисте користили апликацију `Обавештења Тока` , обезбедите да је инсталирана и укључена апликација `Обавештења`. Апликација `Обавештења` обезбеђује неопходне API-је помоћу којих апликација `Обавештења Тока` исправно функционише.\n\n![Конфигурација Обавештења Тока](https://raw.githubusercontent.com/nextcloud/flow_notifications/master/screenshots/configuration.png)\n\nКада се деси догађај коме су испуњени сви услови, корисник ће добити стандардно Nextcloud обавештење.\n\n![Обавештења Тока](https://raw.githubusercontent.com/nextcloud/flow_notifications/master/screenshots/notification.png)",
    "Choose a notification title (optional)" : "Одаберите наслов обавештења (опционо)"
},
"nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);");
