OC.L10N.register(
    "flow_notifications",
    {
    "Send a notification" : "Tuma arifa",
    "Triggers a notification" : "Huanzisha arifa",
    "Flow Notifications" : "Arifa za Mtiririko",
    "Notification action for Nextcloud Flow" : "Kitendo cha arifa kwa mtiririko wa Nextcloud ",
    "Enable users to configure notifications with customized conditions in their Flow configuration.\n\nUsers are empowered to configure a \"Send a notification\" Flow in their personal settings. They can choose between the events being triggered, and other conditions like filetypes, assigned tags, time ranges and more. They can specify an inscription so that when the notification appears they will have context.\n\nTo use the `Flow Notifications` app, ensure that the `Notifications` app is installed and enabled. The `Notifications` app provides the necessary APIs for the `Flow Notifications` app to work correctly.\n\n![Notification Flow Configuration](https://raw.githubusercontent.com/nextcloud/flow_notifications/master/screenshots/configuration.png)\n\nWhen an event happens where all conditions are apply, the user will receive a regular Nextcloud notification.\n\n![Flow Notification](https://raw.githubusercontent.com/nextcloud/flow_notifications/master/screenshots/notification.png)" : "Wezesha watumiaji kusanidi arifa zilizo na hali maalum katika usanidi wao wa Mtiririko.\n\nWatumiaji wamewezeshwa kusanidi Mtiririko wa \"Tuma arifa\" katika mipangilio yao ya kibinafsi. Wanaweza kuchagua kati ya matukio yanayoanzishwa, na masharti mengine kama vile aina za faili, lebo zilizokabidhiwa, masafa ya saa na zaidi. Wanaweza kubainisha maandishi ili arifa inapotokea wawe na muktadha.\n\nIli kutumia programu ya `Arifa za Mtiririko`, hakikisha kuwa programu ya `Arifa` imesakinishwa na kuwashwa. Programu ya `Arifa` hutoa API zinazohitajika ili programu ya `Arifa za Mtiririko` kufanya kazi ipasavyo.\n\n![Usanidi wa Mtiririko wa Arifa](https://raw.githubusercontent.com/nextcloud/flow_notifications/master/screenshots/configuration.png)\n\nTukio linapotokea ambapo masharti yote yanatumika, mtumiaji atapokea arifa ya kawaida ya Nextcloud.\n\n![Arifa ya mtiririko](https://raw.githubusercontent.com/nextcloud/flow_notifications/master/screenshots/notification.png)",
    "Choose a notification title (optional)" : " Chagua kichwa cha arifa (si lazima)"
},
"nplurals=2; plural=(n != 1);");
