OC.L10N.register(
    "flow_notifications",
    {
    "Send a notification" : "ئۇقتۇرۇش ئەۋەتىڭ",
    "Triggers a notification" : "ئۇقتۇرۇشنى قوزغىتىدۇ",
    "Flow Notifications" : "ئاقما ئۇقتۇرۇشى",
    "Notification action for Nextcloud Flow" : "Nextcloud ئېقىمىغا ئۇقتۇرۇش ھەرىكىتى",
    "Enable users to configure notifications with customized conditions in their Flow configuration.\n\nUsers are empowered to configure a \"Send a notification\" Flow in their personal settings. They can choose between the events being triggered, and other conditions like filetypes, assigned tags, time ranges and more. They can specify an inscription so that when the notification appears they will have context.\n\nTo use the `Flow Notifications` app, ensure that the `Notifications` app is installed and enabled. The `Notifications` app provides the necessary APIs for the `Flow Notifications` app to work correctly.\n\n![Notification Flow Configuration](https://raw.githubusercontent.com/nextcloud/flow_notifications/master/screenshots/configuration.png)\n\nWhen an event happens where all conditions are apply, the user will receive a regular Nextcloud notification.\n\n![Flow Notification](https://raw.githubusercontent.com/nextcloud/flow_notifications/master/screenshots/notification.png)" : "ئىشلەتكۈچىلەرنىڭ ئېقىم سەپلىمىسىدە خاسلاشتۇرۇلغان شەرتلەر بىلەن ئۇقتۇرۇشلارنى تەڭشىشىگە يول قويۇڭ.\n\nئىشلەتكۈچىلەر شەخسىي تەڭشەكلىرىدە «ئۇقتۇرۇش ئەۋەتىش» ئېقىمىنى تەڭشىيەلەيدۇ. ئۇلار قوزغىتىلىۋاتقان ۋەقەلەر ۋە ھۆججەت تىپلىرى، بېكىتىلگەن بەلگىلەر، ۋاقىت دائىرىسى قاتارلىق باشقا شەرتلەر ئارىسىدا تاللىيالايدۇ. ئۇلار ئۇقتۇرۇش كۆرۈنگەندە ئۇلارنىڭ مەزمۇنىنى كۆرسىتىدىغان قىلىپ بىر خەت بەلگىلىيەلەيدۇ.\n\n«ئېقىم ئۇقتۇرۇشلىرى» ئەپنى ئىشلىتىش ئۈچۈن، «ئۇقتۇرۇشلار» ئەپنىڭ ئورنىتىلغانلىقى ۋە قوزغىتىلغانلىقىغا كاپالەتلىك قىلىڭ. «ئۇقتۇرۇشلار» ئەپ «ئېقىم ئۇقتۇرۇشلىرى» ئەپنىڭ توغرا ئىشلىشى ئۈچۈن زۆرۈر API بىلەن تەمىنلەيدۇ.\n\n![ئۇقتۇرۇش ئېقىمى سەپلىمىسى](https://raw.githubusercontent.com/nextcloud/flow_notifications/master/screenshots/configuration.png)\n\nبارلىق شەرتلەر قوللىنىلىدىغان ۋەقە يۈز بەرگەندە، ئىشلەتكۈچى دائىملىق Nextcloud ئۇقتۇرۇشىنى تاپشۇرۇۋالىدۇ.\n\n![ئېقىم ئۇقتۇرۇشلىرى](https://raw.githubusercontent.com/nextcloud/flow_notifications/master/screenshots/notification.png)",
    "Choose a notification title (optional)" : "ئۇقتۇرۇش نامىنى تاللاڭ (ئىختىيارىي)"
},
"nplurals=2; plural=(n != 1);");
